#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x $HOME/.config/polybar/launch.sh > /dev/null || $HOME/.config/polybar/launch.sh &
pgrep -x feh --bg-max $HOME/Downloads/samurai-jack-wallpaper-3554x1999.png > /dev/null || feh --bg-max $HOME/Downloads/samurai-jack-wallpaper-3554x1999.png &
pgrep -x picom --config $HOME/.config/picom/picom.conf -b > /dev/null || picom --config $HOME/.config/picom/picom.conf -b &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off